server:
  port: 8762

spring:
  application:
    name: service-hi
  jpa:
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: none
    properties:
      hibernate:
        dialect: com.dingxin.data.jpa.dialect.MyOracle12cDialect
    show-sql: true
    datasource:
      initialize: false
      schema:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@192.168.1.100:1521:orcl
      username: c##djyy
      password: djyy123
      max-idle: 10
      max-wait: 10000
      min-idle: 5
  redis:
    database: 3
    host: 127.0.0.1
    password: issmart
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
      port: 6379
      timeout: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/